//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeAdviser.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingridients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingridients()
        {
            this.Recepi = new HashSet<Recepi>();
        }
    
        public int IngridientId { get; set; }
        public string NameOfIngridient { get; set; }
        public int ProductId { get; set; }
        public string Measurement { get; set; }
        public int Amount { get; set; }
    
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepi> Recepi { get; set; }
    }
}
